export * from "./header/Header";
export * from "./footer/Footer";
export * from "./modal/alert";
export * from "./modal/modal";
export * from "./loginPage/LoginPage";
export * from "./signUpPage/SignUpPage";
export * from "./infoPage/InformationPage";
export * from "./mainPage/MainPage";
export * from "./adminPage/AdminPage";
